---
- name: Create the node_exporter group
  group:
    name: "{{ node_exporter_system_group }}"
    state: present
    system: true
  when: node_exporter_system_group != "root"

- name: Create the node_exporter user
  user:
    name: "{{ node_exporter_system_user }}"
    groups: "{{ node_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: node_exporter_system_user != "root"

- block:
    - name: Download node_exporter binary to local folder
      become: false
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}.tar.gz"
#        checksum: "sha256:{{ node_exporter_checksum }}"
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2

    - name: Unpack node_exporter binary
      shell:
        cmd: tar -xvf "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        chdir: /tmp
        creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}/node_exporter"

    - name: Propagate node_exporter binaries
      copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}/node_exporter"
        dest: "{{ node_exporter_binary_install_dir }}/node_exporter"
        mode: 0755
        owner: "{{ node_exporter_system_user }}"
        group: "{{ node_exporter_system_group }}"
        remote_src: yes
      notify: restart node_exporter
      when: not ansible_check_mode

- name: Install the package libcap2-bin
  apt:
    name: libcap2-bin
    state: present

- name: Add cap_net_bind_service to node_exporter
  capabilities:
    path: "{{ node_exporter_binary_install_dir }}/node_exporter"
    capability: cap_net_bind_service=+eip
    state: present